name: json_ast
version: 1.0.6
description: A library that builds the abstract syntax tree for a JSON string.
homepage: https://github.com/javiercbk/json_ast
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  grapheme_splitter: "^1.0.1"

dev_dependencies:
  test: "^1.3.0"
  path: "^1.5.1"
